/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/guidelines/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active clinical rule pack */
        get: operations["getActiveGuideline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate one transient neonatal jaundice assessment */
        post: operations["evaluateJaundiceAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threshold-curves/{rule_pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get non-patient display points for one gestational age */
        get: operations["getThresholdCurve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/legal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current intended-use, content and privacy notices */
        get: operations["getLegalNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clinical engine readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example nice-cg98-2023-10-31.1 */
        RulePackId: string;
        /** @example 38 */
        GestationalWeeks: number;
        /** @example 2880 */
        AgeMinutes: number;
        /** @example 245 */
        BilirubinUmolL: number;
        /** @enum {string} */
        TriState: "present" | "absent" | "unknown";
        /** @enum {string} */
        MeasurementMethod: "serum" | "transcutaneous";
        /** @enum {string} */
        TreatmentMode: "none" | "phototherapy" | "intensified_phototherapy" | "post_phototherapy" | "post_exchange";
        /** @enum {string} */
        Priority: "emergency" | "immediate" | "urgent" | "treatment" | "timed" | "routine";
        /** @enum {string} */
        ThresholdRelation: "below" | "at" | "above" | "not_available";
        ClinicalFeatures: {
            suspected_or_obvious_jaundice: components["schemas"]["TriState"];
            visible_jaundice: components["schemas"]["TriState"];
            clinically_well: components["schemas"]["TriState"];
            acute_bilirubin_encephalopathy: components["schemas"]["TriState"];
            pale_chalky_stools: components["schemas"]["TriState"];
            dark_urine_stains_nappy: components["schemas"]["TriState"];
            rhesus_haemolytic_disease: components["schemas"]["TriState"];
            abo_haemolytic_disease: components["schemas"]["TriState"];
            infection_suspected: components["schemas"]["TriState"];
            urinary_tract_infection_suspected: components["schemas"]["TriState"];
            routine_metabolic_screen_completed: components["schemas"]["TriState"];
        };
        RiskFactors: {
            previous_sibling_required_phototherapy: components["schemas"]["TriState"];
            exclusive_breastfeeding_intended: components["schemas"]["TriState"];
        };
        Measurement: {
            id: string;
            age_minutes: components["schemas"]["AgeMinutes"];
            total_bilirubin_umol_l: components["schemas"]["BilirubinUmolL"];
            method: components["schemas"]["MeasurementMethod"];
        };
        TreatmentState: {
            mode: components["schemas"]["TreatmentMode"];
            started_age_minutes?: components["schemas"]["AgeMinutes"] | null;
            stopped_age_minutes?: components["schemas"]["AgeMinutes"] | null;
            exchange_completed_age_minutes?: components["schemas"]["AgeMinutes"] | null;
        };
        EvaluationRequest: {
            rule_pack_id: components["schemas"]["RulePackId"];
            gestational_age_completed_weeks: components["schemas"]["GestationalWeeks"];
            assessment_age_minutes: components["schemas"]["AgeMinutes"];
            clinical_features: components["schemas"]["ClinicalFeatures"];
            risk_factors: components["schemas"]["RiskFactors"];
            measurements: components["schemas"]["Measurement"][];
            conjugated_bilirubin_umol_l?: components["schemas"]["BilirubinUmolL"] | null;
            treatment_state: components["schemas"]["TreatmentState"];
        };
        RulePackSummary: {
            id: components["schemas"]["RulePackId"];
            /** @constant */
            guideline_id: "NICE-CG98";
            /** Format: date */
            source_updated_on: string;
            /** @enum {string} */
            status: "draft" | "clinically_validated" | "active" | "retired";
            content_sha256: string;
        };
        SourceReference: {
            /** @constant */
            product_id: "NICE-CG98";
            /** @example 1.4.4 */
            reference: string;
            /** Format: uri */
            url: string;
        };
        ThresholdAssessment: {
            measurement_id: string;
            age_minutes: components["schemas"]["AgeMinutes"];
            phototherapy_threshold_umol_l: number | null;
            phototherapy_relation: components["schemas"]["ThresholdRelation"];
            phototherapy_distance_umol_l: number | null;
            exchange_threshold_umol_l: number | null;
            exchange_relation: components["schemas"]["ThresholdRelation"];
            exchange_distance_umol_l: number | null;
            treatment_decision_eligible: boolean;
        };
        TrendAssessment: {
            older_measurement_id: string;
            newer_measurement_id: string;
            interval_minutes: number;
            rate_umol_l_per_hour: number;
            /** @enum {string} */
            direction: "rising" | "stable" | "falling";
            /** @description True only when both measurements are serum and have distinct validated ages; no additional minimum interval is imposed. */
            reliable_for_rapid_rise: boolean;
            /** @enum {string} */
            rapid_rise_relation: "below" | "at" | "above" | "not_available";
        };
        Timeframe: {
            /** @enum {string} */
            unit: "minutes" | "hours";
            exact?: number;
            minimum?: number;
            maximum?: number;
        };
        Recommendation: {
            code: string;
            priority: components["schemas"]["Priority"];
            /** @enum {string} */
            category: "emergency" | "measurement" | "monitoring" | "phototherapy" | "exchange_transfusion" | "underlying_disease" | "prolonged_jaundice" | "feeding_support" | "information";
            action: string;
            timeframe?: components["schemas"]["Timeframe"] | null;
            rationale: string;
            source_refs: components["schemas"]["SourceReference"][];
            requires_serum_confirmation: boolean;
            /** @constant */
            requires_clinician_confirmation: true;
        };
        Warning: {
            code: string;
            /** @enum {string} */
            category: "clinical" | "scope" | "assay" | "source" | "system" | "legal";
            message: string;
        };
        MissingInformation: {
            pointer: string;
            code: string;
            impact: string;
        };
        DecisionReceipt: {
            /** @constant */
            schema_version: 1;
            digest_sha256: string;
            /** @constant */
            canonicalisation: "JCS-RFC8785";
            /** @constant */
            retained_by_server: false;
        };
        LegalNotices: {
            intended_purpose: string;
            intended_users: string;
            /** @constant */
            uk_only: true;
            professional_use_warning: string;
            local_pathology_warning: string;
            nice_attribution: string;
            non_endorsement: string;
            privacy_summary: string;
            links: {
                [key: string]: string;
            };
        };
        NormalisedInputSummary: {
            gestational_age_completed_weeks: components["schemas"]["GestationalWeeks"];
            assessment_age_minutes: components["schemas"]["AgeMinutes"];
            measurement_count: number;
            latest_measurement_id: string | null;
        };
        EvaluationResponse: {
            /** Format: uuid */
            evaluation_id: string;
            request_id: string;
            /** Format: date-time */
            evaluated_at: string;
            /** @enum {string} */
            mode: "demonstration" | "clinical";
            api_version: string;
            engine_version: string;
            rule_pack: components["schemas"]["RulePackSummary"];
            normalised_input: components["schemas"]["NormalisedInputSummary"];
            thresholds: components["schemas"]["ThresholdAssessment"][];
            trend: components["schemas"]["TrendAssessment"] | null;
            primary_action: components["schemas"]["Recommendation"];
            recommendations: components["schemas"]["Recommendation"][];
            warnings: components["schemas"]["Warning"][];
            missing_information: components["schemas"]["MissingInformation"][];
            suppressed_rules: string[];
            decision_receipt: components["schemas"]["DecisionReceipt"];
            legal: components["schemas"]["LegalNotices"];
        };
        RulePackMetadata: {
            id: components["schemas"]["RulePackId"];
            /** @constant */
            guideline_id: "NICE-CG98";
            /** Format: date */
            source_updated_on: string;
            /** @enum {string} */
            status: "draft" | "clinically_validated" | "active" | "retired";
            content_sha256: string;
            guideline_title: string;
            /**
             * @description ISO 3166-1 alpha-2 code for the United Kingdom; this is not a statement that Great Britain and Northern Ireland share one medical-device route.
             * @constant
             */
            market: "GB";
            /** @constant */
            language: "en-GB";
            scope: {
                gestation_weeks_minimum: number;
                gestation_weeks_maximum: number;
                assessment_age_minutes_maximum: number;
                treatment_age_minutes_maximum: number;
                /** @constant */
                bilirubin_unit: "umol/L";
            };
            sources: {
                id: string;
                /** Format: uri */
                url: string;
                /** Format: date */
                retrieved_on: string;
                sha256: string;
            }[];
            legal: components["schemas"]["LegalNotices"];
        };
        ThresholdCurvePoint: {
            age_minutes: number;
            phototherapy_threshold_umol_l: number;
            exchange_threshold_umol_l: number;
        };
        ThresholdCurve: {
            rule_pack: components["schemas"]["RulePackSummary"];
            gestational_age_completed_weeks: components["schemas"]["GestationalWeeks"];
            /** @enum {integer} */
            resolution_minutes: 1 | 5 | 15 | 30 | 60;
            /** @constant */
            display_only: true;
            points: components["schemas"]["ThresholdCurvePoint"][];
        };
        FieldError: {
            pointer: string;
            code: string;
            message: string;
        };
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri */
            instance: string;
            code: string;
            errors?: components["schemas"]["FieldError"][];
            active_rule_pack_id?: components["schemas"]["RulePackId"] | null;
        };
        HealthStatus: {
            /** @enum {string} */
            status: "live" | "ready";
        };
    };
    responses: {
        /** @description Malformed request */
        BadRequest: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Requested rule pack cannot be evaluated */
        RulePackConflict: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request body exceeds the limit */
        PayloadTooLarge: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Schema or domain validation failed */
        ValidationFailed: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected internal safety failure */
        InternalFailure: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Clinical engine is unavailable */
        Unavailable: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                "X-Request-ID": components["headers"]["RequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        OptionalRequestId: string;
    };
    requestBodies: never;
    headers: {
        RequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getActiveGuideline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active rule-pack metadata */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    /** @example public, max-age=3600 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePackMetadata"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
    evaluateJaundiceAssessment: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["OptionalRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Completed deterministic evaluation */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    /** @example no-store */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["RulePackConflict"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalFailure"];
            503: components["responses"]["Unavailable"];
        };
    };
    getThresholdCurve: {
        parameters: {
            query: {
                gestational_age_completed_weeks: components["schemas"]["GestationalWeeks"];
                resolution_minutes?: 1 | 5 | 15 | 30 | 60;
            };
            header?: never;
            path: {
                rule_pack_id: components["schemas"]["RulePackId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Threshold curve display points */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    /** @example public, max-age=3600 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdCurve"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["RulePackConflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getLegalNotices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Legal and clinical-use notices */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["RequestId"];
                    /** @example public, max-age=3600 */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalNotices"];
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            503: components["responses"]["Unavailable"];
        };
    };
}
